/*
 * WARNING: There is nothing in this file for students to edit or change.
 *          This file is intended to have no student-serviceable code.
 *
 * "Draw" your GUI using the "Design" tab, and remember to give
 * them memorable variable names in the "Properties" panel
 * as well as make them public variables.
 * 
 * For convenience, you may want to set the default visibility of 
 * GUI elements to be public by going to:
 *    The NetBeans Preferences or Settings menu -> Miscellaneous -> GUI Builder
 * Then set Variables Modifier to public.
 */
package viewcontroller;

import models.AllModelsForView;

/**
 * WARNING: Do NOT modify or write any code in this file!
 *
 * @author cheng
 */
public class DrawnView extends AllModelsForView {
    // WARNING: Do NOT modify or write any code in this file!
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    public DrawnView() {
        initComponents();
    }// </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        playerTab = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        colourWheelRecordToggle = new javax.swing.JToggleButton();
        colourWheelSaveButton = new javax.swing.JButton();
        colourWheelPlayBackToggle = new javax.swing.JToggleButton();
        colourWheelList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        colourWheelVolumeSlider = new javax.swing.JSlider();
        colourWheelVolumeLabel = new javax.swing.JLabel();
        wheelLabel = new javax.swing.JLabel();
        colourDisplayLabel = new javax.swing.JLabel();
        thereminTabPanel = new javax.swing.JPanel();
        thereminSaveButton = new javax.swing.JButton();
        thereminPlayBackToggle = new javax.swing.JToggleButton();
        thereminRecordToggle = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        thereminVolumeLabel = new javax.swing.JLabel();
        thereminPanel = new javax.swing.JPanel();
        thereminLabel = new javax.swing.JLabel();
        thereminDepthPanel = new javax.swing.JPanel();
        thereminDepthLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        songUploadButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        uploadSongLabel = new javax.swing.JLabel();

        org.jdesktop.layout.GroupLayout jFrame1Layout = new org.jdesktop.layout.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jFrame2Layout = new org.jdesktop.layout.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        colourWheelRecordToggle.setText("Record");

        colourWheelSaveButton.setText("Save");

        colourWheelPlayBackToggle.setText("Play back");

        colourWheelList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Smooth Circle", "Hexagonal", "Diamond Pattern" }));
        colourWheelList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colourWheelListActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose a colour wheel:");

        jLabel2.setText("Volume: ");

        colourWheelVolumeLabel.setText("50%");

        wheelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wheelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wheel-3-rgb.png"))); // NOI18N
        wheelLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(wheelLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jSeparator1)
                                .addContainerGap())
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(0, 90, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jLabel1)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(colourWheelList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(31, 31, 31))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(colourWheelVolumeLabel)
                                        .add(117, 117, 117))
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(jLabel2)
                                                .add(44, 44, 44)
                                                .add(colourWheelVolumeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .add(jPanel1Layout.createSequentialGroup()
                                                .add(colourWheelRecordToggle)
                                                .add(18, 18, 18)
                                                .add(colourWheelPlayBackToggle)
                                                .add(18, 18, 18)
                                                .add(colourWheelSaveButton)))
                                        .add(29, 29, 29))))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(71, 71, 71)
                        .add(colourDisplayLabel)
                        .add(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(colourWheelVolumeLabel)
                .add(7, 7, 7)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(colourWheelVolumeSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(66, 66, 66)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(colourWheelPlayBackToggle)
                    .add(colourWheelSaveButton)
                    .add(colourWheelRecordToggle))
                .add(77, 77, 77)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(colourWheelList, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .add(82, 82, 82)
                .add(colourDisplayLabel)
                .addContainerGap(131, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, wheelLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        playerTab.addTab("Colour Wheel", jPanel1);

        thereminSaveButton.setText("Save");

        thereminPlayBackToggle.setText("Play back");

        thereminRecordToggle.setText("Record");

        jLabel3.setText("Volume: ");

        thereminVolumeLabel.setText("50%");

        thereminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thereminLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/metal ball.png"))); // NOI18N
        thereminLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        thereminLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        thereminLabel.setMaximumSize(new java.awt.Dimension(448, 448));
        thereminLabel.setMinimumSize(new java.awt.Dimension(448, 448));
        thereminLabel.setOpaque(true);
        thereminLabel.setPreferredSize(new java.awt.Dimension(448, 448));

        org.jdesktop.layout.GroupLayout thereminPanelLayout = new org.jdesktop.layout.GroupLayout(thereminPanel);
        thereminPanel.setLayout(thereminPanelLayout);
        thereminPanelLayout.setHorizontalGroup(
            thereminPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(thereminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(thereminLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 448, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        thereminPanelLayout.setVerticalGroup(
            thereminPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, thereminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(thereminLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        thereminDepthLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/metal ball depth_5.png"))); // NOI18N

        org.jdesktop.layout.GroupLayout thereminDepthPanelLayout = new org.jdesktop.layout.GroupLayout(thereminDepthPanel);
        thereminDepthPanel.setLayout(thereminDepthPanelLayout);
        thereminDepthPanelLayout.setHorizontalGroup(
            thereminDepthPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(thereminDepthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(thereminDepthLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );
        thereminDepthPanelLayout.setVerticalGroup(
            thereminDepthPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(thereminDepthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(thereminDepthLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout thereminTabPanelLayout = new org.jdesktop.layout.GroupLayout(thereminTabPanel);
        thereminTabPanel.setLayout(thereminTabPanelLayout);
        thereminTabPanelLayout.setHorizontalGroup(
            thereminTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(thereminTabPanelLayout.createSequentialGroup()
                .add(thereminPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 191, Short.MAX_VALUE)
                .add(thereminTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, thereminTabPanelLayout.createSequentialGroup()
                        .add(thereminTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(thereminDepthPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(thereminTabPanelLayout.createSequentialGroup()
                                .add(thereminRecordToggle)
                                .add(18, 18, 18)
                                .add(thereminPlayBackToggle)
                                .add(18, 18, 18)
                                .add(thereminSaveButton))
                            .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 274, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(28, 28, 28))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, thereminTabPanelLayout.createSequentialGroup()
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(thereminVolumeLabel)
                        .add(117, 117, 117))))
        );
        thereminTabPanelLayout.setVerticalGroup(
            thereminTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(thereminTabPanelLayout.createSequentialGroup()
                .add(92, 92, 92)
                .add(thereminTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(thereminSaveButton)
                    .add(thereminPlayBackToggle)
                    .add(thereminRecordToggle))
                .add(68, 68, 68)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(8, 8, 8)
                .add(thereminTabPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(thereminVolumeLabel))
                .add(18, 18, 18)
                .add(thereminDepthPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(thereminPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        playerTab.addTab("Theremin", thereminTabPanel);

        songUploadButton.setText("Upload song");

        playButton.setText("Play");

        stopButton.setText("Stop");

        uploadSongLabel.setText("Upload a song!");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(90, 90, 90)
                        .add(songUploadButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(playButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(stopButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(178, 178, 178)
                        .add(uploadSongLabel)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(112, 112, 112)
                .add(uploadSongLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(songUploadButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(playButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(stopButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        playerTab.addTab("Music Player", jPanel3);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(playerTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(playerTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colourWheelListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colourWheelListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colourWheelListActionPerformed
    // WARNING: Do NOT modify or write any code in this file!
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel colourDisplayLabel;
    public javax.swing.JComboBox colourWheelList;
    public javax.swing.JToggleButton colourWheelPlayBackToggle;
    public javax.swing.JToggleButton colourWheelRecordToggle;
    public javax.swing.JButton colourWheelSaveButton;
    public javax.swing.JLabel colourWheelVolumeLabel;
    public javax.swing.JSlider colourWheelVolumeSlider;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton playButton;
    private javax.swing.JTabbedPane playerTab;
    public javax.swing.JButton songUploadButton;
    public javax.swing.JButton stopButton;
    public javax.swing.JLabel thereminDepthLabel;
    private javax.swing.JPanel thereminDepthPanel;
    public javax.swing.JLabel thereminLabel;
    private javax.swing.JPanel thereminPanel;
    public javax.swing.JToggleButton thereminPlayBackToggle;
    public javax.swing.JToggleButton thereminRecordToggle;
    public javax.swing.JButton thereminSaveButton;
    public javax.swing.JPanel thereminTabPanel;
    public javax.swing.JLabel thereminVolumeLabel;
    public javax.swing.JLabel uploadSongLabel;
    public javax.swing.JLabel wheelLabel;
    // End of variables declaration//GEN-END:variables
}
